# Default values for controlplane.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: wundergraph/cosmo/controlplane
  registry: ghcr.io
  pullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is the chart appVersion.
  version: 'latest'

deploymentStrategy: {}

imagePullSecrets: []

# -- String to partially override common.names.fullname template (will maintain the release name)
nameOverride: ''

# -- String to fully override common.names.fullname template
fullnameOverride: ''

# -- Allows to set additional environment variables on the container. Useful for global application non-specific settings.
extraEnvVars: []
#extraEnvVars:
#  - name: NODE_OPTIONS
#    value: "--max-old-space-size=1536"

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ''

serviceAnnotations: {}

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 3001

ingress:
  #  enabled: true
  #  className: ""
  #  annotations: {}
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
  #    - host: controlplane.wundergraph.local
  #      paths:
  #        - path: /
  #          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

#initContainers:
#  - name: init-postgresql
#    image: busybox:1.28
#    imagePullPolicy: "IfNotPresent"
#    command: ['sh', '-c', 'until nslookup {{ include "postgresql.fullname" . }}; do echo waiting for postgresql; sleep 2; done;']

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

volumes: []

volumeMounts: []

tolerations: []

affinity: {}

# -- Sets the [pod disruption budget](https://kubernetes.io/docs/tasks/run-application/configure-pdb/) for Deployment pods
podDisruptionBudget: {}

# -- Set to existing PriorityClass name to control pod preemption by the scheduler
priorityClassName: ''

# -- Sets the [termination grace period](https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#hook-handler-execution) for Deployment pods
terminationGracePeriodSeconds: 60

probes:
  # -- Configure readiness probe
  readiness:
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 5
    timeoutSeconds: 3
    periodSeconds: 5
    failureThreshold: 5
  # -- Configure liveness probe
  liveness:
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 10
    timeoutSeconds: 5
    failureThreshold: 5
    periodSeconds: 10

########################
# Global configuration #
########################

#global:
#  controlplane:
#    webUrl: "http://controlplane.local"
#    jwtSecret: "changeme"

#############################
# Application configuration #
#############################

configuration:
  logLevel: 'info'
  allowedOrigins:
    - '*'
  debugSQL: false
  authRedirectUri: 'http://controlplane.wundergraph.local/v1/auth/callback'
  databaseUrl: 'postgres://postgres:changeme@cosmo-postgresql:5432/controlplane'
  # -- When connecting to a postgres instance over TLS. Accept a cert in PEM format (as one-line with \n) or file.
  databaseTlsCa: ''
  databaseTlsCert: ''
  databaseTlsKey: ''
  redisPassword: ''
  redisHost: 'cosmo-redis-master'
  redisPort: 6379
  # -- When connecting to a redis instance over TLS. Accept a cert in PEM format (as one-line with \n) or file.
  redisTlsCa: ''
  redisTlsCert: ''
  redisTlsKey: ''
  clickhouseDsn: 'http://default:changeme@cosmo-clickhouse:8123?database=cosmo'
  clickhouseMigrationDsn: 'clickhouse://default:changeme@cosmo-clickhouse:9000?database=cosmo'
  webhookUrl: ''
  webhookSecret: ''
  githubAppClientId: ''
  githubAppClientSecret: ''
  githubAppId: ''
  githubAppPrivateKey: ''
  githubAppWebhookSecret: ''
  slackAppClientId: ''
  slackAppClientSecret: ''
  s3StorageUrl: 'http://minio:changeme@cosmo-minio:9000/cosmo'
  smtpUsername: ''
  smtpPassword: ''
  stripeSecretKey: ''
  stripeWebhookSecret: ''
  # -- The default billing plan, eg `developer@1`
  defaultBillingPlan: ''
  openAiApiKey: ''
  # -- URL of the CDN to use for serving router configs and persistent operations
  cdnBaseUrl: 'http://cosmo-cdn:8787'

# -- Existing secret in the same namespace containing the ControlPlane Secrets. The secret keys have to match with current secret.
existingSecret: ""
