# yaml-language-server: $schema=./pkg/config/config.schema.json

# Ensure you have YAML Language Server installed in your editor to get the best experience with this file.
# Please keep this file empty if you don't want to override the defaults.

version: '1'

cors:
  allow_headers:
    - X-Forwarded-For

compliance:
  redact_ip_addresses:
    enabled: false