# yaml-language-server: $schema=./pkg/config/config.schema.json

# See pkg/config/config.go for the full list of configuration options.
# This file is used to debugging purposes only.

version: "1"

execution_config:
  provider: "s3"
  enabled: true
  endpoint: "http://localhost:9000"
  bucket: "router"