---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "controlplane.fullname" . }}-configmap
  annotations:
    # Support for k14s.io. This annotation will produce a redeployment when the configmap changes.
    kapp.k14s.io/versioned: ""
  labels:
    {{- include "controlplane.labels" . | nindent 4 }}
data:
  host: "0.0.0.0"
  port: "{{ .Values.service.port }}"
  logLevel: "{{ .Values.configuration.logLevel }}"
  allowedOrigins: "{{ join "," .Values.configuration.allowedOrigins }}"
  webBaseUrl: "{{ .Values.global.studio.webUrl }}"
  debugSQL: "{{ .Values.configuration.debugSQL }}"
  authRedirectUri: "{{ .Values.configuration.authRedirectUri }}"
  keycloakRealm: "{{ .Values.global.keycloak.realm }}"
  keycloakApiUrl: "{{ .Values.global.keycloak.apiUrl }}"
  keycloakFrontendUrl: "{{ .Values.global.keycloak.webUrl }}"
  keycloakClientId: "{{ .Values.global.keycloak.clientId }}"
  keycloakLoginRealm: "{{ .Values.global.keycloak.loginRealm }}"
  webhookUrl: "{{ .Values.configuration.webhookUrl }}"
  githubAppClientId: "{{ .Values.configuration.githubAppClientId }}"
  githubAppId: "{{ .Values.configuration.githubAppId }}"
  slackAppClientId: "{{ .Values.configuration.slackAppClientId }}"
  defaultBillingPlan: "{{ .Values.configuration.defaultBillingPlan }}"
  redisHost: "{{ .Values.configuration.redisHost }}"
  redisPort: "{{ .Values.configuration.redisPort }}"
  smtpEnabled: "{{ .Values.configuration.smtp.enabled }}"
  {{- if .Values.configuration.smtp.enabled }}
  smtpHost: "{{ .Values.configuration.smtp.host }}"
  smtpPort: "{{ .Values.configuration.smtp.port }}"
  smtpSecure: "{{ .Values.configuration.smtp.secure }}"
  smtpRequireTls: "{{ .Values.configuration.smtp.requireTls }}"
  {{- end }}
  prometheusEnabled: "{{ .Values.configuration.prometheus.enabled }}"
  {{- if .Values.configuration.prometheus.enabled }}
  prometheusHost: "{{ .Values.configuration.prometheus.host }}"
  prometheusPort: "{{ .Values.configuration.prometheus.port }}"
  prometheusPath: "{{ .Values.configuration.prometheus.path }}"
  {{ end }}
