---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "studio.fullname" . }}
  annotations:
    # Support for k14s.io. This annotation will produce a redeployment when the configmap changes.
    kapp.k14s.io/versioned: ""
  labels:
    {{- include "studio.labels" . | nindent 4 }}
data:
  controlplaneWebUrl: "{{ .Values.global.controlplane.webUrl }}"
  studioWebUrl: "{{ .Values.global.studio.webUrl }}"
  slackClientId: "{{ .Values.configuration.slackClientId }}"
  customHeadScripts: "{{ .Values.configuration.customHeadScripts }}"
  stripePublishableKey: "{{ .Values.configuration.stripePublishableKey }}"
