apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    readOnly: false
    editable: true
    jsonData:
      httpMethod: POST
      manageAlerts: true
  - name: Pyroscope
    type: grafana-pyroscope-datasource
    url: http://pyroscope:4040
    readOnly: false
    editable: false
    jsonData:
      httpMethod: POST
      manageAlerts: true
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    readOnly: false
    editable: true
    jsonData:
      defaultDatabase: cosmo
      port: 9000
      host: clickhouse
      username: $__env{CLICKHOUSE_USER}
    secureJsonData:
      password: $__env{CLICKHOUSE_PASSWORD}
