name: Helm Deployment
on:
  pull_request:
    paths:
      - "helm/**/*"
      - ".github/workflows/helm-ci.yaml"

concurrency:
  group: ${{github.workflow}}-${{github.head_ref}}
  cancel-in-progress: true

env:
  CI: true

jobs:
  build_test:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/go

      - name: Install tools
        run: go install github.com/yannh/kubeconform/cmd/kubeconform@v0.6.3

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Install bitnami repo
        run: helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Setup Carvel tools
        uses: carvel-dev/setup-action@v2
        with:
          only: kapp, kbld
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Smoke test if the Carvel tools are working
        run: |
          kapp version
          kbld version

      - name: start minikube
        if: github.event_name == 'pull_request' && !startsWith(github.head_ref, 'release-please--')
        id: minikube
        uses: medyagh/setup-minikube@v0.0.18
        with:
          addons: ingress

      - name: Deploy to minikube
        if: github.event_name == 'pull_request' && !startsWith(github.head_ref, 'release-please--')
        working-directory: ./helm
        run: make deploy KAPP_ARGS="-y --logs-all"
