name: Build and Push Docker images

on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'
    paths-ignore:
      - 'docs/*/**'
      - 'helm/**'
      - 'scripts/**'

  pull_request:
    paths-ignore:
      - 'docs/*/**'
      - 'helm/**'
      - 'scripts/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

concurrency:
  group: ${{github.workflow}}-${{github.head_ref}}
  cancel-in-progress: true

jobs:
  build-and-push-image:
    timeout-minutes: 30
    strategy:
      matrix:
        include:
          - container_name: cdn
            dockerfile: cdn-server/Dockerfile
            context_path: .
            platforms: linux/amd64,linux/arm64
          - container_name: controlplane
            dockerfile: controlplane/Dockerfile
            context_path: .
            platforms: linux/amd64,linux/arm64
          - container_name: router
            dockerfile: router/Dockerfile
            context_path: router
            platforms: linux/amd64,linux/arm64
          - container_name: studio
            dockerfile: studio/Dockerfile
            context_path: .
            platforms: linux/amd64,linux/arm64
          - container_name: keycloak
            dockerfile: keycloak/Dockerfile
            context_path: keycloak
            platforms: linux/amd64,linux/arm64
          - container_name: otelcollector
            dockerfile: otelcollector/Dockerfile
            context_path: otelcollector
            platforms: linux/amd64,linux/arm64
          - container_name: graphqlmetrics
            dockerfile: graphqlmetrics/Dockerfile
            context_path: graphqlmetrics
            platforms: linux/amd64,linux/arm64
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.container_name }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
            # use custom value instead of git tag
            type=match,pattern=[a-zA-Z-_]+@(.*),group=1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Container registry (With write access)
        uses: docker/login-action@v3
        if: github.event.pull_request.head.repo.full_name == github.repository
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to Github Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.2.0

      # This is a limitation of GitHub. Only organization members can push to GitHub Container Registry
      # For now, we will disable the push step for Pull Requests
      - name: Build Docker image (No push)
        uses: docker/build-push-action@v5
        with:
          push: false
          file: ${{ matrix.dockerfile }}
          context: ${{ matrix.context_path }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ matrix.platforms }}
          build-args: |
            VERSION=${{ github.sha }}
