name: Release Preview

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - 'main'
    paths-ignore:
      - 'docs*/**'
      - '*.md'

concurrency:
  group: ${{github.workflow}}-${{github.head_ref}}
  cancel-in-progress: false

env:
  CI: true

jobs:
  version:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/node

      - name: Install
        run: |
          pnpm add -g @lerna-lite/cli@2.5.1 @lerna-lite/publish@2.5.1 @lerna-lite/version@2.5.1 @commitlint/config-conventional@17.6.6

      - name: Generate next release (dry-run)
        run: pnpm run release-preview --yes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Show CHANGELOG.md
        run: echo -e "\`\`\`diff\n$(git --no-pager diff './*/CHANGELOG.md')\n\`\`\`" >> $GITHUB_STEP_SUMMARY
