name: Release

on:
  workflow_dispatch:

concurrency:
  group: Production
  cancel-in-progress: false

env:
  CI: true

jobs:
  stable-version:
    # https://docs.npmjs.com/generating-provenance-statements#publishing-packages-with-provenance-via-github-actions
    permissions:
      id-token: write
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN_WORKFLOW_PUBLISH }}

      - uses: ./.github/actions/node
        with:
          working-directory: ${{ env.WORKING_DIRECTORY }}

      - run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        shell: bash
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Generate code
        run: pnpm buf generate --template buf.ts.gen.yaml

      - name: Check if git is not dirty after generating files
        run: git diff --no-ext-diff --exit-code

      - name: Build
        run: pnpm run --filter='!./studio' build

      - name: Publish packages & Create Github Releases
        run: |
          git config --global user.email "bot@wundergraph.com"
          git config --global user.name "hardworker-bot"
          pnpm release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_WORKFLOW_PUBLISH }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
